#!/usr/bin/env python3
"""
Short script that will delete all blank Keep notes from a directory
"""

from pathlib import Path
import json
import numpy as np

def main(directory: str):
    directory = Path(directory)

    # collect all files
    tot_counter = 0
    json_files = []
    html_files = []
    others = []
    for file in directory.iterdir():
        tot_counter += 1
        if file.suffix == ".html":
            html_files.append(file)
        elif file.suffix == ".json":
            json_files.append(file)
        else:
            others.append(file)

    print(f"Total files: {tot_counter}")
    print(f"HTML files: {len(html_files)}")
    print(f"JSON files: {len(json_files)}")
    print(f"Other files: {len(others)}")

    # search files for patterns
    titled: list[bool] = []
    has_text: list[bool] = []
    labeled: list[bool] = []

    titles = []
    texts = []
    labels = []
    for file in json_files:
        # check json metadata to see if this note is blank
        with file.open("r", encoding="utf-8") as f:
            data = json.load(f)

            title = data.get("title", "")
            text = data.get("textContent", "")
            labels = data.get("labels", [])

            if title:
                titled.append(True)
            else:
                titled.append(False)

            if text:
                has_text.append(True)
            else:
                has_text.append(False)

            if labels:
                labeled.append(True)
            else:
                labeled.append(False)

            titles.append(title)
            texts.append(text)
            labels.append(labels)

    print(f"Titleless notes: {titled.count(False)}") 
    print(f"Textless notes: {has_text.count(False)}") 
    print(f"Labelless notes: {labeled.count(False)}") 

    text_and_title = [a & b for a, b in zip(titled, has_text)]
    text_and_label = [a & b for a, b in zip(labeled, has_text)]

    no_text_and_title = [b & (not a) for a, b in zip(has_text, titled)]
    print(f"No text but title: {no_text_and_title.count(True)}")

    text_and_no_title = [a & (not b) for a, b in zip(has_text, titled)]
    print(f"Has text but no title: {text_and_no_title.count(True)}")

    text_and_no_labels = [a & (not b) for a, b in zip(has_text, labeled)]
    print(f"Has text but no labels: {text_and_no_labels.count(True)}")

    no_text_and_labels = [(not a) & b for a, b in zip(has_text, labeled)]
    print(f"No text but labels: {no_text_and_labels.count(True)}")

    no_text_no_title_no_labels = [(not a) & (not b) & (not c) for a, b, c in zip(has_text, titled, labeled)]
    print(f"Nothing: {no_text_no_title_no_labels.count(True)}")

    # delete textless notes
    for i, file in enumerate(json_files):
        if not has_text[i]:

        

if __name__=="__main__":
    directory = "./tests/keep/"
    main(directory)
