#!/usr/bin/env python3
# main.py
# CLI for application

import argparse
import rich.console, rich.rule
from enum import Enum

from src.organizer import BrainOrganizer

class CmdResult(Enum):
    NONE = 0      # continue with current iteration
    CONTINUE = 2  # move to next iteration
    EXIT = 1      # break out of repl

class BrainCLI:
    def __init__(self, brain: BrainOrganizer, top_k: int):
        self.brain = brain
        self.top_k = top_k

        self.console = rich.console.Console()

        self.commands = {
                "query" : self.do_query,
                "cluster" : self.do_cluster,

                "clear" : self.do_clear,
                "cls" : self.do_clear,

                "exit" : self.do_exit,
                "q" : self.do_exit,
                "quit" : self.do_exit
                }

    # ---------------------------------- COMMANDS for REPL -------------------------------
    def do_query(self, *args) -> CmdResult:
        pass

    def do_cluster(self, *args) -> CmdResult:
        pass

    def do_clear(self, *args) -> CmdResult:
        self.console.clear()
        return CmdResult.CONTINUE

    def do_exit(self, *args) -> CmdResult:
        return CmdResult.EXIT
 
    def handle_commands(self, line: str) -> CmdResult:
        """ Returns 0, 1, 2 after executing command """
        cmd, *args = line[1:].strip().split(" ")

        func = self.commands.get(cmd)
        if func is None:
            self.console.print(f"[red]{line} is not a recognized command[/red]")
            return CmdResult.CONTINUE
        
        result = func(*args)
        return result

    # ---------------------------------- PRINTING for REPL -------------------------------
    def print_search_results(self, results) -> None:
        for i, result in enumerate(results):
            self.console.print(f"[bold cyan]Result # {i+1}[/bold cyan]")
            self.console.print(f"{result.to_preview()}")
            self.console.print(rich.rule.Rule())

    def print_cluster_results(self, results) -> None:
        self.console.print(f"[blue]Clusters[/blue]")
        self.console.print(rich.rule.Rule())
        self.console.print(results.to_preview())

    # ----------------------------------- REPL ------------------------------------------
    def repl(self) -> None:
        while True:
            try:
                # read a line of input
                line = input(f"brain> ")

                # check for command and run command
                if line.startswith(":"):
                    # result can be 0 (do nothing), 1 (continue to next input), 2 (exit program)
                    result = self.handle_commands(line)
                    if result == CmdResult.EXIT:
                        break
                    if result == CmdResult.CONTINUE:
                        continue
                
                # run specific method based on brain mode
                if self.mode == Mode.QUERY:
                    search_results = self.brain.search_notes(line, self.top_k)
                    self.print_results(search_results)
                elif self.mode == Mode.CLUSTER:
                    try:
                        num_clusters = int(line)
                    except ValueError:
                        self.console.print(f"[yellow]{line} cannot be converted to type int[/yellow]")
                        continue
                    clusters = self.brain.cluster_notes(num_clusters)
                    self.print_results(clusters.values())
                elif self.mode == Mode.TIMELINE:
                    self.console.print("[yellow]Timeline mode not supported yet[/yellow]")
                    
 
            except EOFError:
                # handles Ctrl+D and Ctrl+Z
                self.console.print("\nEOF received. Exiting...")
                break

def main():
    parser = argparse.ArgumentParser(
            prog='SemanticSearcher',
            description='Searches Keep notes for notes that best match a query semantically',
            )
    parser.add_argument('directory', type=str)
    parser.add_argument('-q', '--query', type=str)
    parser.add_argument('-c', '--cluster', type=int)
    parser.add_argument('-k', '--top-k', type=int, default=5)
    parser.add_argument('-m', '--model-name', type=str, default='sentence-transformers/all-MiniLM-L6-v2')
    
    args = parser.parse_args()
    brain = BrainOrganizer.from_keep_directory(args.directory, args.model_name)
    brain_cli = BrainCLI(brain, args.top_k)

    # treat the brain as its own interactive model, 
    # but allow a straight query result if prompted with '--query'
    # the default mode of the repl is to accept queries and spit out results
    if args.query:
        search_results = brain.search_notes(args.query, args.top_k)
        brain_cli.print_search_results(search_results)
    elif args.cluster:
        clusters = brain.cluster_notes(args.cluster)
        brain_cli.print_cluster_results(clusters)
    else:
        brain_cli.repl()

if __name__=="__main__":
    main()
